// DTAI course rosters, keyed by section
const SECTIONS = {
  sectionA: {
    label: "Section A",
    roster: [
  {roll:"IEP26001", name:"GAURAV KARWA"},
  {roll:"PGP40297", name:"ALISHA LAKRA"},
  {roll:"PGP41004", name:"AMEY RAJUL SHAMKUWAR"},
  {roll:"PGP41009", name:"BHOOMIKA YADAV"},
  {roll:"PGP41019", name:"LATESH BAYAD"},
  {roll:"PGP41035", name:"RISHI DEVENDRA SINGH"},
  {roll:"PGP41036", name:"RITWIK SARKAR"},
  {roll:"PGP41037", name:"RIYA"},
  {roll:"PGP41038", name:"RIYA AGARWAL"},
  {roll:"PGP41039", name:"RUDRI PANDYA"},
  {roll:"PGP41042", name:"SAMALA SRAVANTHI"},
  {roll:"PGP41050", name:"SIDDHARTH TARKUNDE"},
  {roll:"PGP41059", name:"ABHIRUP SARKAR"},
  {roll:"PGP41068", name:"AYUSH BARYA"},
  {roll:"PGP41086", name:"KSHITIJ BHARDWAJ"},
  {roll:"PGP41116", name:"YASHIKA CHUGH"},
  {roll:"PGP41120", name:"ADITYA TIDKE"},
  {roll:"PGP41124", name:"AMBARISH BORAH"},
  {roll:"PGP41136", name:"HAZEL MARY KAMPAKKARAN"},
  {roll:"PGP41137", name:"HRISHIKESH KUMAR"},
  {roll:"PGP41179", name:"AMOL GUPTA"},
  {roll:"PGP41180", name:"ANSHUMAN NAYAK"},
  {roll:"PGP41189", name:"DOKINA RAMA KRISHNA"},
  {roll:"PGP41191", name:"GAYATHRI ARVIND"},
  {roll:"PGP41193", name:"GOVIND J S"},
  {roll:"PGP41194", name:"HARSHIT MALPANI"},
  {roll:"PGP41227", name:"TANMAY BHATT"},
  {roll:"PGP41233", name:"AAKARSH CHOUREY"},
  {roll:"PGP41238", name:"ARGADE SHUBHAM POPATRAO"},
  {roll:"PGP41242", name:"AYUSH RAVINDRA SHEGOKAR"},
  {roll:"PGP41245", name:"CHAUDHARI TEJAS SANJAY"},
  {roll:"PGP41260", name:"JATIN SINGH"},
  {roll:"PGP41268", name:"NIKITA KALO"},
  {roll:"PGP41274", name:"SAJJA BHARGAVA MADHUKAR"},
  {roll:"PGP41279", name:"SHANTANU AGARWAL"},
  {roll:"PGP41287", name:"VIBHUTE PRATHAMESH SANJIVKUMAR"},
  {roll:"PGP41288", name:"VIPUL TYAGI"},
  {roll:"PGP41292", name:"AHMED KADAVILPARAMBIL ISMAIL"},
  {roll:"PGP41293", name:"AMIT BHARTI"},
  {roll:"PGP41294", name:"ANANDU VINAYAK"},
  {roll:"PGP41297", name:"APOORVA GUPTA"},
  {roll:"PGP41302", name:"CHETAN DUGGIRALA"},
  {roll:"PGP41305", name:"DIVANSHU NARANG"},
  {roll:"PGP41308", name:"GOHIL AKHIL UMESHCHANDRA"},
  {roll:"PGP41311", name:"OMPRAKASH TRIPATHY"},
  {roll:"PGP41312", name:"KAPRE AJINKYA NARENDRA"},
  {roll:"PGP41329", name:"SARAH SHRIVASTAVA"},
  {roll:"PGP41330", name:"SHREYANSH PATEL"},
  {roll:"PGP41332", name:"SIDDHI WALUNJ"},
  {roll:"PGP41339", name:"UTKARSH KUMAR"},
  {roll:"PGP41340", name:"VAASVI KUMAR"},
  {roll:"PGP41342", name:"VISHAL KUMAR SINGH"},
  {roll:"PGP41344", name:"WANGSHEINLA LONGKUMER"},
  {roll:"PGP41348", name:"AANANYA PAWAR"},
  {roll:"PGP41361", name:"DONGA HARSHA VARDHAN"},
  {roll:"PGP41366", name:"KARRI HIMA SATYA HEMANTH"},
  {roll:"PGP41371", name:"KUNAL NITIN SURYAWANSHI"},
  {roll:"PGP41376", name:"MANURKAR PRATIK PADMAKAR"},
  {roll:"PGP41377", name:"MOHIT JAIN"},
  {roll:"PGP41396", name:"SHIVAM SARASWAT"},
  {roll:"PGP41416", name:"BHAVYA SOOD"},
  {roll:"PGP41420", name:"HARINI SUGUNURI"},
  {roll:"PGP41426", name:"KUMAR ASHWINI"},
  {roll:"PGP41467", name:"ANURAG SHYAMSUNDER KALANTRI"},
  {roll:"PGP41471", name:"BORSE PIYUSH SATISH"},
  {roll:"PGP41492", name:"MEGHNA SHARMA"},
  {roll:"PGP41505", name:"SHUBHRO JYOTI DEY"},
  {roll:"PGP41514", name:"TRUSHIL CHAUHAN"},
]
  },
  sectionB: {
    label: "Section B",
    roster: [
      {roll:"PGP40285", name:"UDMALE MAYUR TUKARAM"},
      {roll:"PGP41006", name:"ANSHUL PARATE"},
      {roll:"PGP41011", name:"DEEPAK CHARNAWAT"},
      {roll:"PGP41012", name:"GOKUL HARI NAIR"},
      {roll:"PGP41030", name:"PRATHAMESH KUMBHAR"},
      {roll:"PGP41032", name:"PUSHKAR MANDAL"},
      {roll:"PGP41043", name:"SANJAY SINGH SALORA"},
      {roll:"PGP41052", name:"SREERAJ RAMESAN"},
      {roll:"PGP41054", name:"THADCHAN M"},
      {roll:"PGP41057", name:"VIDUSHI SINGH"},
      {roll:"PGP41061", name:"ADITYA BHATNAGAR"},
      {roll:"PGP41066", name:"ANJALI KANKARWAL"},
      {roll:"PGP41080", name:"HRITHIK RAJ BOLLA"},
      {roll:"PGP41090", name:"NIDHINA O V"},
      {roll:"PGP41100", name:"SASWATA SAHA"},
      {roll:"PGP41103", name:"SHINJAN PATRA"},
      {roll:"PGP41107", name:"SRISHTI LAHIRI"},
      {roll:"PGP41109", name:"SUPRATIK SARKAR"},
      {roll:"PGP41114", name:"VYAWHARE CHAITANYA RAVINDRA"},
      {roll:"PGP41126", name:"ASTHA SAIKIA"},
      {roll:"PGP41134", name:"GOYAL NISHTHA BRAJESH"},
      {roll:"PGP41138", name:"KALLEPALLI HEMANTH"},
      {roll:"PGP41144", name:"MADHUGOGUL P"},
      {roll:"PGP41153", name:"NITYA RAWAL"},
      {roll:"PGP41170", name:"SNEHAJIT DEY"},
      {roll:"PGP41197", name:"KAUSHAL KUMAR"},
      {roll:"PGP41209", name:"PRACHI GANDHI"},
      {roll:"PGP41219", name:"SAMALA NISHANTH REDDY"},
      {roll:"PGP41231", name:"YASHWANTH M"},
      {roll:"PGP41249", name:"DEBOJYOTI DAS"},
      {roll:"PGP41251", name:"DESAI YASHRAJ VIJAY"},
      {roll:"PGP41253", name:"DINAKAR D M"},
      {roll:"PGP41262", name:"LIDZUSA BESU"},
      {roll:"PGP41265", name:"MOHIT VIJAY"},
      {roll:"PGP41266", name:"NANDANA JAYAN"},
      {roll:"PGP41269", name:"P VYSHNAV SHENOY"},
      {roll:"PGP41270", name:"PARINISTHA DEV DAS"},
      {roll:"PGP41275", name:"SAKETH CHAMALLA"},
      {roll:"PGP41284", name:"UDIT SHARMA"},
      {roll:"PGP41289", name:"VIVEK UMRAO BANGAR"},
      {roll:"PGP41291", name:"AAYUSH JAIN"},
      {roll:"PGP41298", name:"ARITRA GURU"},
      {roll:"PGP41309", name:"GOURAV"},
      {roll:"PGP41310", name:"K VENKITA NARAYANAN"},
      {roll:"PGP41316", name:"MALLENIPALLI GOUTHAM SIDDHARTH"},
      {roll:"PGP41317", name:"MEHTA DHRUV DHARMESHBHAI"},
      {roll:"PGP41318", name:"NUPUR KAMALAKAR DANGE"},
      {roll:"PGP41319", name:"PATEL CHARMIL KANTIBHAI"},
      {roll:"PGP41353", name:"ANKIT YADAV"},
      {roll:"PGP41367", name:"KAUSIK BALA"},
      {roll:"PGP41375", name:"MANDALA VEDHAVYASH"},
      {roll:"PGP41380", name:"PAKALAPATI PRATYUSHA"},
      {roll:"PGP41385", name:"PRIYA MANDAL"},
      {roll:"PGP41394", name:"SHARAD DUBEY"},
      {roll:"PGP41395", name:"SHELAR SHRUTI RAMESH"},
      {roll:"PGP41401", name:"VEMAKOTI GOPA GAYATRI"},
      {roll:"PGP41405", name:"A KARTHICKEYAN"},
      {roll:"PGP41418", name:"ESHAAN SHARMA"},
      {roll:"PGP41448", name:"SUSONGITA MANDAL"},
      {roll:"PGP41455", name:"VUNDI ANJURA"},
      {roll:"PGP41461", name:"AKANKSHA BHATIA"},
      {roll:"PGP41462", name:"AKHIL KRISHNA R"},
      {roll:"PGP41468", name:"BADAVATH GAYATHRI"},
      {roll:"PGP41508", name:"SONAWANE NIKHIL SANJAY"},
      {roll:"PGP41512", name:"TANVIR SINGH SAHNI"},
      {roll:"PHD-26015", name:"PIYUSH KUMAR"},
    ]
  }
};

// Backward-compatible default (Section A) — kept so nothing else breaks silently
const ROSTER = SECTIONS.sectionA.roster;
